Repository kafbat/kafka-ui, pull requests merged in 2024-11, with the labels that each got.

#655 Infra: Fix e2e compose
  documentation/compose/e2e-tests.yaml
Labels: type/bug, scope/infra, status/triage/completed

#639 Chore: Deps: Use latest 17 jre image
  .github/dependabot.yml
  api/Dockerfile
Labels: scope/backend, type/dependencies, status/triage/completed

#649 BE: Set default message polling mode
  api/src/main/java/io/kafbat/ui/controller/MessagesController.java
Labels: scope/backend, type/chore, status/triage/completed

#651 BE: Support sending null headers
  api/src/main/java/io/kafbat/ui/serdes/ProducerRecordCreator.java
  api/src/test/java/io/kafbat/ui/service/SendAndReadTests.java
Labels: type/enhancement, scope/backend, area/messages, status/triage/completed

#670 Docs: Fix typo
  README.md
Labels: type/chore, status/triage/completed

#646 FE: Filters: Display CEL help when editing filter
  frontend/src/components/Topics/Topic/Messages/Filters/AddEditFilterContainer.tsx
  frontend/src/components/Topics/Topic/Messages/Filters/Filters.styled.ts
  frontend/src/components/Topics/Topic/Messages/Filters/__tests__/AddEditFilterContainer.spec.tsx
Labels: type/enhancement, scope/frontend, area/messages, status/triage/completed

#676 BE: Logger unification
  api/src/main/java/io/kafbat/ui/config/auth/OAuthSecurityConfig.java
Labels: scope/backend, type/chore, status/triage/completed
