Repository kafbat/kafka-ui, pull requests merged in 2024-04, with the labels that each got.

#220 BE: Fix double LDAP bean init
  api/src/main/java/io/kafbat/ui/KafkaUiApplication.java
  api/src/main/java/io/kafbat/ui/config/auth/LdapSecurityConfig.java
Labels: scope/backend, type/chore, area/auth, status/triage/completed

#267 RBAC: Fix 403 when viewing audit topic messages
  api/src/main/java/io/kafbat/ui/model/rbac/Resource.java
Labels: scope/backend, type/bug, area/rbac, status/triage/completed

#255 Update issue templates
  .github/ISSUE_TEMPLATE/bug.yml
  .github/ISSUE_TEMPLATE/feature.yml
  .github/workflows/welcome-first-time-contributors.yml
Labels: scope/infra, type/chore, status/triage/completed

#277 Allow smart filters endpoint in r/o mode
  api/src/main/java/io/kafbat/ui/config/ReadOnlyModeFilter.java
Labels: scope/backend, type/bug, type/regression, status/triage/completed

#285 BE: Sanitize connection.uri for mongo
  api/src/main/java/io/kafbat/ui/service/KafkaConfigSanitizer.java
  api/src/test/java/io/kafbat/ui/service/KafkaConfigSanitizerTest.java
Labels: scope/backend, type/chore, status/triage/completed

#297 FE: Chore: Add React Query Devtool
  frontend/package.json
  frontend/pnpm-lock.yaml
  frontend/src/components/App.tsx
Labels: scope/frontend, type/chore, status/triage/completed

#301 FE: Remove lodash lib
  frontend/.eslintrc.json
  frontend/package.json
  frontend/pnpm-lock.yaml
  frontend/src/components/App.tsx
  frontend/src/components/Connect/Details/Actions/__tests__/Actions.spec.tsx
  frontend/src/components/Connect/New/New.tsx
  frontend/src/components/ConsumerGroups/Details/Details.tsx
  frontend/src/components/Topics/Topic/Messages/Filters/utils.ts
  frontend/src/components/Topics/Topic/SendMessage/utils.ts
  frontend/src/components/common/NewTable/utils/__test__/updateSortingState.spec.ts
  frontend/src/lib/functions/__tests__/compact.spec.ts
  frontend/src/lib/functions/__tests__/groupBy.spec.ts
  frontend/src/lib/functions/compact.ts
  frontend/src/lib/functions/groupBy.ts
  frontend/src/lib/functions/keyBy.ts
  frontend/src/lib/hooks/api/kafkaConnect.ts
  frontend/src/widgets/ClusterConfigForm/schema.ts
  frontend/src/widgets/ClusterConfigForm/utils/getJaasConfig.ts
Labels: scope/frontend, type/chore, status/triage/completed

#298 BE: Fix user matching in OauthAuthorityExtractor
  api/src/main/java/io/kafbat/ui/service/rbac/extractor/OauthAuthorityExtractor.java
Labels: scope/backend, type/bug, type/chore, status/triage/completed

#306 BE: Bump aws-msk-iam-auth dependency
  api/pom.xml
Labels: scope/backend, type/dependencies, status/triage/completed

#308 Sonar: Configure to ignore e2e module code
  pom.xml
Labels: scope/infra, type/chore, status/triage/completed

#314 Disabling LDAP auto-configuration to prevent LDAP health check failed
  api/src/main/java/io/kafbat/ui/KafkaUiApplication.java
Labels: scope/backend, type/bug, type/regression, status/triage/completed

#321 Bugfix: Cannot reuse filter display name
  frontend/src/components/Topics/Topic/Messages/Filters/Filters.tsx
Labels: scope/frontend, type/bug, area/messages, status/triage/completed

#227 FE: Redesign menu
  e2e-tests/src/main/java/io/kafbat/ui/screens/panels/NaviSideBar.java
  e2e-tests/src/main/java/io/kafbat/ui/screens/schemas/SchemaCreateForm.java
  e2e-tests/src/main/java/io/kafbat/ui/screens/topics/TopicCreateEditForm.java
  e2e-tests/src/main/java/io/kafbat/ui/utilities/WebUtil.java
  e2e-tests/src/test/java/io/kafbat/ui/smokesuite/schemas/SchemasTest.java
  frontend/src/components/App.styled.ts
  frontend/src/components/Nav/ClusterMenu.tsx
  frontend/src/components/Nav/ClusterMenu/ClusterMenu.tsx
  frontend/src/components/Nav/ClusterMenu/__tests__/ClusterMenu.spec.tsx
  frontend/src/components/Nav/ClusterMenuItem.tsx
  frontend/src/components/Nav/ClusterTab/ClusterTab.styled.ts
  frontend/src/components/Nav/ClusterTab/ClusterTab.tsx
  frontend/src/components/Nav/Menu/MenuItem.tsx
  frontend/src/components/Nav/Menu/MenuTab.tsx
  frontend/src/components/Nav/Menu/__tests__/MenuItem.spec.tsx
  frontend/src/components/Nav/Menu/__tests__/MenuTab.spec.tsx
  frontend/src/components/Nav/Menu/__tests__/MenuTab.styled.spec.tsx
  frontend/src/components/Nav/Menu/styled.ts
  frontend/src/components/Nav/Nav.styled.ts
  frontend/src/components/Nav/Nav.tsx
  frontend/src/components/Nav/__tests__/ClusterMenuItem.spec.tsx
  frontend/src/components/NavBar/NavBar.styled.ts
  frontend/src/components/NavBar/NavBar.tsx
  frontend/src/components/NavBar/__tests__/NavBar.spec.tsx
  frontend/src/components/PageContainer/PageContainer.styled.ts
  frontend/src/components/PageContainer/PageContainer.tsx
  frontend/src/components/PageContainer/__tests__/PageContainer.spec.tsx
  frontend/src/components/common/Button/Button.styled.ts
  frontend/src/components/common/Button/Button.tsx
  frontend/src/components/common/Icons/MenuIcon.tsx
  frontend/src/lib/hooks/__tests__/useBoolean.spec.ts
  frontend/src/lib/hooks/useBoolean.ts
  frontend/src/lib/hooks/useScreenSize.ts
  frontend/src/theme/__tests__/hexToRgba.spec.ts
  frontend/src/theme/hexToRgba.ts
  frontend/src/theme/theme.ts
Labels: scope/frontend, type/refactor, area/ux, status/triage/completed
