Repository kafbat/kafka-ui, pull requests merged in 2024-09, with the labels that each got.

#530 Auth: Support Azure Entra (Event Hub with Kafka Protocol)
  api/pom.xml
  api/src/main/java/io/kafbat/ui/config/auth/azure/AzureEntraLoginCallbackHandler.java
  api/src/main/java/io/kafbat/ui/config/auth/azure/AzureEntraOAuthBearerToken.java
  api/src/test/java/io/kafbat/ui/config/auth/azure/AzureEntraLoginCallbackHandlerTest.java
  api/src/test/java/io/kafbat/ui/config/auth/azure/AzureEntraOAuthBearerTokenTest.java
  frontend/src/lib/constants.ts
  frontend/src/widgets/ClusterConfigForm/schema.ts
  frontend/src/widgets/ClusterConfigForm/utils/getJaasConfig.ts
  frontend/src/widgets/ClusterConfigForm/utils/transformFormDataToPayload.ts
Labels: type/enhancement, scope/frontend, scope/backend, area/auth, status/triage/completed

#553 BE: Chore: Polishing
  api/src/main/java/io/kafbat/ui/config/auth/azure/AzureEntraLoginCallbackHandler.java
  api/src/main/java/io/kafbat/ui/config/auth/azure/AzureEntraOAuthBearerToken.java
Labels: scope/backend, type/chore, status/triage/completed

#558 Bugfix: SIGSEV in docker container on ARM64
  api/pom.xml
Labels: scope/backend, type/bug, status/triage/completed

#380 FE: Fix refetching data on window focus
  frontend/src/components/Schemas/Edit/Edit.tsx
  frontend/src/components/Topics/Topic/Edit/Edit.tsx
  frontend/src/lib/constants.ts
  frontend/src/lib/hooks/api/__tests__/schema.spec.ts
  frontend/src/lib/hooks/api/__tests__/topics.spec.ts
  frontend/src/lib/hooks/api/schemas.ts
  frontend/src/lib/hooks/api/topics.ts
Labels: scope/frontend, type/bug, status/triage/completed

#518 BE: Make gh version check timeout configurable
  api/src/main/java/io/kafbat/ui/service/ApplicationInfoService.java
  api/src/main/java/io/kafbat/ui/util/GithubReleaseInfo.java
  api/src/test/java/io/kafbat/ui/AbstractIntegrationTest.java
  api/src/test/java/io/kafbat/ui/service/ApplicationInfoServiceTest.java
  api/src/test/java/io/kafbat/ui/util/GithubReleaseInfoTest.java
Labels: type/enhancement, scope/backend, status/triage/completed
