Repository kafbat/kafka-ui, pull requests merged in 2025-02, with the labels that each got.

#796 Docs: Fix broken composes
  .dev/dev.yaml
  documentation/compose/auth-context.yaml
  documentation/compose/cluster-sr-auth.yaml
  documentation/compose/e2e-tests.yaml
  documentation/compose/kafbat-ui.yaml
  documentation/compose/kafka-ssl-components.yaml
  documentation/compose/kafka-ssl.yml
  documentation/compose/ui-acl-with-zk.yaml
  documentation/compose/ui-connectors-auth.yaml
  documentation/compose/ui-jmx-secured.yml
  documentation/compose/ui-ldap.yaml
  documentation/compose/ui-sasl.yaml
  documentation/compose/ui-serdes.yaml
  documentation/compose/ui-with-jmx-exporter.yaml
Labels: type/chore, impact/documentation, status/triage/completed

#830 BE: Chore: Upgrade spring boot to 3.4.2
  pom.xml
Labels: scope/backend, type/security, type/dependencies, status/triage/completed

#832 BE: Clean some Sonar issues
  api/pom.xml
  api/src/main/java/io/kafbat/ui/exception/CelException.java
  api/src/main/java/io/kafbat/ui/exception/GlobalErrorWebExceptionHandler.java
  api/src/main/java/io/kafbat/ui/model/rbac/provider/Provider.java
  api/src/main/java/io/kafbat/ui/serdes/builtin/Base64Serde.java
  api/src/main/java/io/kafbat/ui/serdes/builtin/HexSerde.java
  api/src/main/java/io/kafbat/ui/serdes/builtin/ProtobufFileSerde.java
  api/src/main/java/io/kafbat/ui/service/audit/AuditRecord.java
  api/src/main/java/io/kafbat/ui/service/integration/odd/ConnectorInfo.java
  api/src/main/java/io/kafbat/ui/service/integration/odd/schema/JsonSchemaExtractor.java
  api/src/main/java/io/kafbat/ui/service/ksql/KsqlGrammar.java
  api/src/main/java/io/kafbat/ui/service/metrics/JmxMetricsFormatter.java
  api/src/main/java/io/kafbat/ui/util/jsonschema/AvroJsonSchemaConverter.java
  api/src/test/java/io/kafbat/ui/KafkaConnectServiceTests.java
  api/src/test/java/io/kafbat/ui/KafkaConsumerGroupTests.java
  api/src/test/java/io/kafbat/ui/KafkaConsumerTests.java
  api/src/test/java/io/kafbat/ui/KafkaTopicCreateTests.java
  api/src/test/java/io/kafbat/ui/ReadOnlyModeTests.java
  api/src/test/java/io/kafbat/ui/SchemaRegistryServiceTests.java
  api/src/test/java/io/kafbat/ui/config/auth/azure/AzureEntraLoginCallbackHandlerTest.java
  api/src/test/java/io/kafbat/ui/config/auth/azure/AzureEntraOAuthBearerTokenTest.java
  api/src/test/java/io/kafbat/ui/controller/ApplicationConfigControllerTest.java
  api/src/test/java/io/kafbat/ui/emitter/MessageFiltersTest.java
  api/src/test/java/io/kafbat/ui/serdes/builtin/HexSerdeTest.java
  api/src/test/java/io/kafbat/ui/serdes/builtin/ProtobufRawSerdeTest.java
  api/src/test/java/io/kafbat/ui/service/ApplicationInfoServiceTest.java
  api/src/test/java/io/kafbat/ui/service/ConfigTest.java
  api/src/test/java/io/kafbat/ui/service/LogDirsTest.java
  api/src/test/java/io/kafbat/ui/service/OffsetsResetServiceTest.java
  api/src/test/java/io/kafbat/ui/service/SchemaRegistryPaginationTest.java
  api/src/test/java/io/kafbat/ui/service/SendAndReadTests.java
  api/src/test/java/io/kafbat/ui/service/TopicsServicePaginationTest.java
  api/src/test/java/io/kafbat/ui/service/audit/AuditIntegrationTest.java
  api/src/test/java/io/kafbat/ui/service/masking/DataMaskingTest.java
Labels: scope/backend, type/chore, status/triage/completed

#838 BE: Chore: Remove unused classes
  api/src/main/java/io/kafbat/ui/config/auth/condition/ActiveDirectoryCondition.java
  api/src/main/java/io/kafbat/ui/model/BrokerMetrics.java
  api/src/main/java/io/kafbat/ui/model/InternalClusterMetrics.java
Labels: scope/backend, type/chore, status/triage/completed

#449 FE: Topics: Save field previews into local storage
  frontend/src/components/Topics/Topic/Messages/MessagesTable.tsx
  frontend/src/components/Topics/Topic/Messages/__test__/MessagesTable.spec.tsx
  frontend/src/lib/hooks/useLocalStorage.ts
Labels: type/enhancement, scope/frontend, hacktoberfest-accepted, area/messages, status/triage/manual, status/triage/completed

#840 BE: Auth: Support LDAPS for AD
  api/pom.xml
  api/src/main/java/io/kafbat/ui/config/auth/LdapSecurityConfig.java
  api/src/main/java/io/kafbat/ui/util/CustomSslSocketFactory.java
  api/src/test/java/io/kafbat/ui/AbstractActiveDirectoryIntegrationTest.java
  api/src/test/java/io/kafbat/ui/ActiveDirectoryLdapTest.java
  api/src/test/java/io/kafbat/ui/ActiveDirectoryLdapsTest.java
  api/src/test/java/io/kafbat/ui/container/ActiveDirectoryContainer.java
Labels: type/enhancement, scope/backend, area/auth, status/triage/completed

#784 Create Kafka Admin Client outside of the Parallel scheduler thread pool
  api/src/main/java/io/kafbat/ui/service/AdminClientServiceImpl.java
Labels: scope/backend, type/bug, status/triage/completed

#859 Docs: Get back AMI link
  README.md
Labels: type/chore, impact/documentation, status/triage/completed

#849 BE: SR: Fix HTTP 400 with slashes in schema name
  api/src/main/java/io/kafbat/ui/config/GeneralSecurityConfig.java
Labels: scope/backend, type/bug, area/sr, status/triage/completed

#851 BE: overwrite json-smart
  pom.xml
Labels: status/triage/manual, status/triage/completed

#875 Fix supply AdminClient creation
  api/src/main/java/io/kafbat/ui/service/AdminClientServiceImpl.java
Labels: scope/backend, type/bug, status/triage/completed

#876 Validate config values before start
  api/pom.xml
  api/src/main/java/io/kafbat/ui/config/ClustersProperties.java
Labels: type/enhancement, scope/backend, status/triage/completed
