Repository kafbat/kafka-ui, pull requests merged in 2025-05, with the labels that each got.

#1013 BE: Auth: Support GCP IAM Auth
  api/build.gradle
  frontend/src/lib/constants.ts
  frontend/src/widgets/ClusterConfigForm/schema.ts
  frontend/src/widgets/ClusterConfigForm/utils/getJaasConfig.ts
  frontend/src/widgets/ClusterConfigForm/utils/transformFormDataToPayload.ts
  gradle/libs.versions.toml
Labels: type/enhancement, scope/backend, area/auth, status/triage/completed

#1050 BE: Messages: Implement null filtering for CEL
  api/src/main/java/io/kafbat/ui/emitter/MessageFilters.java
  api/src/test/java/io/kafbat/ui/emitter/MessageFiltersTest.java
Labels: scope/backend, type/bug, area/messages, status/triage/completed

#1070 BE: Internal: Support version getter from `metadata.version`
  api/src/main/java/io/kafbat/ui/service/ReactiveAdminClient.java
  api/src/main/java/io/kafbat/ui/util/MetadataVersion.java
Labels: type/enhancement, scope/backend, status/triage/manual, status/triage/completed

#1075 FE: Auth: Add GCP IAM missing enums
  frontend/src/widgets/ClusterConfigForm/schema.ts
Labels: scope/frontend, type/bug, area/auth, status/triage/completed

#1078 Typescript autotesting start
  e2e-playwright/Dockerfile
  e2e-playwright/README.md
  e2e-playwright/config/cucumber.js
  e2e-playwright/package-lock.json
  e2e-playwright/package.json
  e2e-playwright/src/features/Topics.feature
  e2e-playwright/src/features/TopicsCreate.feature
  e2e-playwright/src/features/navigation.feature
  e2e-playwright/src/helper/browsers/browserManager.ts
  e2e-playwright/src/helper/env/.env.prod
  e2e-playwright/src/helper/env/.env.stage
  e2e-playwright/src/helper/env/env.ts
  e2e-playwright/src/helper/report/init.ts
  e2e-playwright/src/helper/report/report.ts
  e2e-playwright/src/helper/types/env.d.ts
  e2e-playwright/src/helper/util/logger.ts
  e2e-playwright/src/helper/wrapper/PlaywrightWrappers.ts
  e2e-playwright/src/helper/wrapper/assert.ts
  e2e-playwright/src/hooks/hooks.ts
  e2e-playwright/src/hooks/pageFixture.ts
  e2e-playwright/src/pages/BaseLocators.ts
  e2e-playwright/src/pages/Brokers/BrokersLocators.ts
  e2e-playwright/src/pages/Connectors/ConnectorsLocators.ts
  e2e-playwright/src/pages/Consumers/ConsumersLocators.ts
  e2e-playwright/src/pages/Dashboard/DashboardLocators.ts
  e2e-playwright/src/pages/KSQLDB/ksqldbLocators.ts
  e2e-playwright/src/pages/Panel/PanelLocators.ts
  e2e-playwright/src/pages/SchemaRegistry/SchemaRegistryLocators.ts
  e2e-playwright/src/pages/Topics/TopicsCreateLocators.ts
  e2e-playwright/src/pages/Topics/TopicsLocators.ts
  e2e-playwright/src/services/commonFunctions.ts
  e2e-playwright/src/services/uiHelper.ts
  e2e-playwright/src/steps/Topics.steps.ts
  e2e-playwright/src/steps/TopicsCreate.steps.ts
  e2e-playwright/src/steps/navigation.steps.ts
  e2e-playwright/src/support/customWorld.ts
  e2e-playwright/tsconfig.json
Labels: status/triage/manual, status/triage/completed

#1077 BE: Messages: Format non-string headers
  api/src/main/java/io/kafbat/ui/serdes/ConsumerRecordDeserializer.java
  api/src/main/java/io/kafbat/ui/util/ContentUtils.java
  api/src/test/java/io/kafbat/ui/util/ContentUtilsTest.java
Labels: type/enhancement, scope/backend, area/messages, area/serde, status/triage/completed

#1092 Reworked locators, Added Eslint, Code refactoring, cleaning
  e2e-playwright/.eslintignore
  e2e-playwright/.eslintrc.json
  e2e-playwright/config/cucumber.js
  e2e-playwright/eslint.config.js
  e2e-playwright/package-lock.json
  e2e-playwright/package.json
  e2e-playwright/src/features/Topics.feature
  e2e-playwright/src/features/TopicsCreate.feature
  e2e-playwright/src/features/navigation.feature
  e2e-playwright/src/helper/browsers/browserManager.ts
  e2e-playwright/src/helper/types/env.d.ts
  e2e-playwright/src/helper/wrapper/PlaywrightWrappers.ts
  e2e-playwright/src/helper/wrapper/assert.ts
  e2e-playwright/src/hooks/hooks.ts
  e2e-playwright/src/hooks/pageFixture.ts
  e2e-playwright/src/pages/BaseLocators.ts
  e2e-playwright/src/pages/Brokers/BrokersLocators.ts
  e2e-playwright/src/pages/Connectors/ConnectorsLocators.ts
  e2e-playwright/src/pages/Consumers/ConsumersLocators.ts
  e2e-playwright/src/pages/Dashboard/DashboardLocators.ts
  e2e-playwright/src/pages/KSQLDB/ksqldbLocators.ts
  e2e-playwright/src/pages/Locators.ts
  e2e-playwright/src/pages/Panel/PanelLocators.ts
  e2e-playwright/src/pages/SchemaRegistry/SchemaRegistryLocators.ts
  e2e-playwright/src/pages/Topics/TopicsCreateLocators.ts
  e2e-playwright/src/pages/Topics/TopicsLocators.ts
  e2e-playwright/src/playwright.config.ts
  e2e-playwright/src/services/commonFunctions.ts
  e2e-playwright/src/services/uiHelper.ts
  e2e-playwright/src/steps/Topics.steps.ts
  e2e-playwright/src/steps/TopicsCreate.steps.ts
  e2e-playwright/src/steps/navigation.steps.ts
  e2e-playwright/src/support/PlaywrightWorld.ts
  e2e-playwright/src/support/customWorld.ts
  e2e-playwright/tsconfig.json
Labels: status/triage/manual, status/triage/completed

#1103 Housekeeping. Removed Superbuilders. Fixed deprecations
  .github/workflows/backend_tests.yml
  api/build.gradle
  api/src/main/antlr/ksql/KsqlGrammar.g4
  api/src/main/java/io/kafbat/ui/config/McpConfig.java
  api/src/main/java/io/kafbat/ui/controller/ApplicationConfigController.java
  api/src/main/java/io/kafbat/ui/controller/AuthorizationController.java
  api/src/main/java/io/kafbat/ui/exception/GlobalErrorWebExceptionHandler.java
  api/src/main/java/io/kafbat/ui/mapper/ClusterMapper.java
  api/src/main/java/io/kafbat/ui/mapper/DescribeLogDirsMapper.java
  api/src/main/java/io/kafbat/ui/mapper/DynamicConfigMapper.java
  api/src/main/java/io/kafbat/ui/mapper/KafkaConnectMapper.java
  api/src/main/java/io/kafbat/ui/model/InternalLogDirStats.java
  api/src/main/java/io/kafbat/ui/serdes/CustomSerdeLoader.java
  api/src/main/java/io/kafbat/ui/serdes/builtin/sr/Serialize.java
  api/src/main/java/io/kafbat/ui/service/AdminClientServiceImpl.java
  api/src/main/java/io/kafbat/ui/service/BrokerService.java
  api/src/main/java/io/kafbat/ui/service/ReactiveAdminClient.java
  api/src/main/java/io/kafbat/ui/service/StatisticsService.java
  api/src/main/java/io/kafbat/ui/util/ContentUtils.java
  api/src/main/java/io/kafbat/ui/util/DynamicConfigOperations.java
  api/src/main/java/io/kafbat/ui/util/jsonschema/JsonAvroConversion.java
  api/src/test/java/io/kafbat/ui/AbstractIntegrationTest.java
  api/src/test/java/io/kafbat/ui/config/RegexBasedProviderAuthorityExtractorTest.java
  api/src/test/java/io/kafbat/ui/container/KafkaConnectContainer.java
  api/src/test/java/io/kafbat/ui/container/KsqlDbContainer.java
  api/src/test/java/io/kafbat/ui/container/SchemaRegistryContainer.java
  api/src/test/java/io/kafbat/ui/emitter/MessageFiltersTest.java
  api/src/test/java/io/kafbat/ui/producer/KafkaTestProducer.java
  api/src/test/java/io/kafbat/ui/service/audit/AuditServiceTest.java
  api/src/test/java/io/kafbat/ui/service/audit/AuditWriterTest.java
  api/src/test/java/io/kafbat/ui/service/quota/ClientQuotaServiceTest.java
  api/src/test/java/io/kafbat/ui/service/rbac/AccessControlServiceRbacDisabledTest.java
  api/src/test/java/io/kafbat/ui/service/rbac/AccessControlServiceRbacEnabledTest.java
  contract/build.gradle
  contract/src/main/resources/swagger/kafbat-ui-api.yaml
  e2e-tests/build.gradle
  frontend/build.gradle
  serde-api/src/main/java/io/kafbat/ui/serde/api/DeserializeResult.java
  serde-api/src/main/java/io/kafbat/ui/serde/api/PropertyResolver.java
  serde-api/src/main/java/io/kafbat/ui/serde/api/RecordHeader.java
  serde-api/src/main/java/io/kafbat/ui/serde/api/RecordHeaders.java
  serde-api/src/main/java/io/kafbat/ui/serde/api/SchemaDescription.java
  serde-api/src/main/java/io/kafbat/ui/serde/api/Serde.java
Labels: status/triage/completed
