Repository kafbat/kafka-ui, pull requests merged in 2025-08, with the labels that each got.

#1233 Chore: Fix grammar
  api/src/main/java/io/kafbat/ui/serdes/builtin/ProtobufFileSerde.java
Labels: type/chore, status/triage/completed

#1229 Docs: Updated feature list
  README.md
Labels: type/chore, impact/documentation, status/triage/completed

#1250 BE: Contracts: Enable openapi contracts validator
  contract/build.gradle
  contract/src/main/resources/swagger/kafbat-ui-api.yaml
  gradle/libs.versions.toml
Labels: scope/backend, type/chore, status/triage/completed

#1266 FE: Don't omit milliseconds in timestamps
  frontend/src/components/Topics/Topic/Messages/Message.tsx
  frontend/src/components/Topics/Topic/Messages/MessageContent/MessageContent.tsx
  frontend/src/components/Topics/Topic/Messages/__test__/Message.spec.tsx
  frontend/src/lib/dateTimeHelpers.ts
Labels: type/enhancement, scope/frontend, area/ux, status/triage/manual, status/triage/completed

#1272 FE: Some CVE fixes
  frontend/package.json
  frontend/pnpm-lock.yaml
  frontend/src/components/Topics/Topic/Messages/Filters/__tests__/Filters.spec.tsx
Labels: scope/frontend, type/security, status/triage/completed

#1287 Infra: Exclude Springboot dependencies from the `other-dependencies` dependabot group
  .github/dependabot.yml
Labels: scope/infra, type/chore, status/triage/completed
