Repository kafbat/kafka-ui, pull requests merged in 2025-03, with the labels that each got.

#874 BE: Allow overriding producer and consumer properties
  api/src/main/java/io/kafbat/ui/config/ClustersProperties.java
  api/src/main/java/io/kafbat/ui/model/KafkaCluster.java
  api/src/main/java/io/kafbat/ui/service/ConsumerGroupService.java
  api/src/main/java/io/kafbat/ui/service/KafkaClusterFactory.java
  api/src/main/java/io/kafbat/ui/service/MessagesService.java
  api/src/test/java/io/kafbat/ui/AbstractIntegrationTest.java
  api/src/test/java/io/kafbat/ui/service/ConfigTest.java
Labels: type/enhancement, scope/backend, status/triage/completed

#783 Infra: Add gradle p.1
  .gitignore
  api/Dockerfile
  api/build.gradle
  api/pom.xml
  api/src/main/java/io/kafbat/ui/config/WebclientProperties.java
  api/src/main/java/io/kafbat/ui/config/auth/RoleBasedAccessControlProperties.java
  build.gradle
  contract/build.gradle
  e2e-tests/build.gradle
  frontend/build.gradle
  frontend/vite.config.ts
  gradle.properties
  gradle/libs.versions.toml
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  serde-api/build.gradle
  serde-api/gradle.properties
  settings.gradle
Labels: scope/backend, scope/infra, status/triage/completed

#885 Infra: Migrate CI to Gradle
  .devcontainer/devcontainer.json
  .github/CODEOWNERS
  .github/dependabot.yml
  .github/workflows/aws_ami_publish.yml
  .github/workflows/backend_main.yml
  .github/workflows/backend_pr.yml
  .github/workflows/backend_tests.yml
  .github/workflows/block_merge.yml
  .github/workflows/branch-deploy.yml
  .github/workflows/build-public-image.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/cve_checks.yml
  .github/workflows/docker_build.yml
  .github/workflows/docker_publish.yml
  .github/workflows/e2e-manual.yml
  .github/workflows/e2e-pr.yml
  .github/workflows/e2e-run.yml
  .github/workflows/frontend_pr.yml
  .github/workflows/frontend_tests.yml
  .github/workflows/main.yml
  .github/workflows/pr_linter.yml
  .github/workflows/release-serde-api.yml
  .github/workflows/release.yml
  .github/workflows/separate_env_public_create.yml
  .github/workflows/workflow_linter.yml
  .gitignore
  api/Dockerfile
  api/build.gradle
  api/src/main/resources/static/static/css/bootstrap.min.css
  api/src/main/resources/static/static/css/signin.css
  build.gradle
  contract/build.gradle
  e2e-tests/README.md
  e2e-tests/build.gradle
  e2e-tests/selenoid/config/browsers-ci.json
  e2e-tests/selenoid/config/browsers-local.json
  e2e-tests/selenoid/selenoid-ci.yaml
  e2e-tests/selenoid/selenoid-local.yaml
  e2e-tests/src/main/java/io/kafbat/ui/settings/BaseSource.java
  e2e-tests/src/main/java/io/kafbat/ui/settings/drivers/WebDriver.java
  frontend/build.gradle
  frontend/vite.config.ts
  gradle/libs.versions.toml
  serde-api/build.gradle
Labels: type/enhancement, scope/infra, impact/documentation, status/triage/completed

#884 Infra: Migrate build system from maven to gradle
  .devcontainer/devcontainer.json
  .github/CODEOWNERS
  .github/dependabot.yml
  .github/workflows/aws_ami_publish.yml
  .github/workflows/backend_main.yml
  .github/workflows/backend_pr.yml
  .github/workflows/backend_tests.yml
  .github/workflows/block_merge.yml
  .github/workflows/branch-deploy.yml
  .github/workflows/build-public-image.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/cve_checks.yml
  .github/workflows/docker_build.yml
  .github/workflows/docker_publish.yml
  .github/workflows/e2e-manual.yml
  .github/workflows/e2e-pr.yml
  .github/workflows/e2e-run.yml
  .github/workflows/frontend_pr.yml
  .github/workflows/frontend_tests.yml
  .github/workflows/main.yml
  .github/workflows/pr_linter.yml
  .github/workflows/release-serde-api.yml
  .github/workflows/release.yml
  .github/workflows/separate_env_public_create.yml
  .github/workflows/workflow_linter.yml
  .gitignore
  api/Dockerfile
  api/build.gradle
  api/pom.xml
  api/src/main/java/io/kafbat/ui/config/WebclientProperties.java
  api/src/main/java/io/kafbat/ui/config/auth/RoleBasedAccessControlProperties.java
  api/src/main/resources/static/static/css/bootstrap.min.css
  api/src/main/resources/static/static/css/signin.css
  build.gradle
  contract/build.gradle
  e2e-tests/README.md
  e2e-tests/build.gradle
  e2e-tests/selenoid/config/browsers-ci.json
  e2e-tests/selenoid/config/browsers-local.json
  e2e-tests/selenoid/selenoid-ci.yaml
  e2e-tests/selenoid/selenoid-local.yaml
  e2e-tests/src/main/java/io/kafbat/ui/settings/BaseSource.java
  e2e-tests/src/main/java/io/kafbat/ui/settings/drivers/WebDriver.java
  frontend/build.gradle
  frontend/vite.config.ts
  gradle.properties
  gradle/libs.versions.toml
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  serde-api/build.gradle
  serde-api/gradle.properties
  settings.gradle
Labels: type/enhancement, scope/infra, impact/documentation

#897 BE: Fix deps and build
  .github/workflows/backend_tests.yml
  .github/workflows/frontend_tests.yml
  api/build.gradle
  gradle/libs.versions.toml
Labels: scope/infra, type/dependencies, status/triage/completed

#902 Bump dependencies
  .github/workflows/frontend_tests.yml
  gradle/libs.versions.toml
Labels: scope/frontend, scope/backend, scope/infra, type/dependencies, status/triage/completed

#873 Wizard: Support Editing masking
  frontend/src/lib/constants.ts
  frontend/src/widgets/ClusterConfigForm/ClusterConfigForm.styled.ts
  frontend/src/widgets/ClusterConfigForm/Sections/Masking.tsx
  frontend/src/widgets/ClusterConfigForm/index.tsx
  frontend/src/widgets/ClusterConfigForm/schema.ts
  frontend/src/widgets/ClusterConfigForm/types.ts
  frontend/src/widgets/ClusterConfigForm/utils/getInitialFormData.ts
  frontend/src/widgets/ClusterConfigForm/utils/transformFormDataToPayload.ts
Labels: type/enhancement, scope/frontend, area/wizard, status/triage/completed

#901 BE: Fix spring boot build info population
  api/build.gradle
Labels: scope/backend, type/bug, status/triage/completed

#900 FE: Messages: Add schema validation support for more json-schema version refs
  frontend/package.json
  frontend/pnpm-lock.yaml
  frontend/src/components/Topics/Topic/SendMessage/__test__/utils.spec.ts
  frontend/src/components/Topics/Topic/SendMessage/utils.ts
Labels: scope/frontend, type/bug, area/messages, status/triage/completed

#915 Infra: Remove Maven related files
  .mvn/jvm.config
  .mvn/wrapper/maven-wrapper.jar
  .mvn/wrapper/maven-wrapper.properties
  api/pom.xml
  contract/pom.xml
  e2e-tests/pom.xml
  mvnw
  mvnw.cmd
  pom.xml
  serde-api/pom.xml
  settings.xml
Labels: scope/infra, type/chore, status/triage/completed

#866 Wizard: Support Editing serdes
  frontend/src/widgets/ClusterConfigForm/ClusterConfigForm.styled.ts
  frontend/src/widgets/ClusterConfigForm/Sections/Serdes/PropertiesFields.tsx
  frontend/src/widgets/ClusterConfigForm/Sections/Serdes/Serdes.tsx
  frontend/src/widgets/ClusterConfigForm/index.tsx
  frontend/src/widgets/ClusterConfigForm/schema.ts
  frontend/src/widgets/ClusterConfigForm/types.ts
  frontend/src/widgets/ClusterConfigForm/utils/getInitialFormData.ts
  frontend/src/widgets/ClusterConfigForm/utils/transformFormDataToPayload.ts
Labels: type/enhancement, scope/frontend, area/wizard, status/triage/manual, status/triage/completed

#453 FE: Topics: Remember user polling options
  frontend/src/components/Topics/Topic/Messages/Filters/Filters.tsx
  frontend/src/components/Topics/Topic/Messages/Filters/__tests__/Filters.spec.tsx
  frontend/src/components/common/Search/Search.tsx
  frontend/src/components/common/Select/Select.tsx
  frontend/src/lib/constants.ts
  frontend/src/lib/hooks/api/topicMessages.tsx
  frontend/src/lib/hooks/useMessagesFilters.ts
  frontend/src/lib/hooks/useMessagesFiltersFields.ts
  frontend/src/lib/types.ts
Labels: type/enhancement, scope/frontend, hacktoberfest-accepted, area/topics, area/messages, status/triage/completed

#398 UX: Custom colored cluster menu
  build.gradle
  e2e-tests/README.md
  e2e-tests/build.gradle
  e2e-tests/src/main/java/io/kafbat/ui/screens/connectors/ConnectorDetails.java
  e2e-tests/src/main/java/io/kafbat/ui/screens/schemas/SchemaDetails.java
  e2e-tests/src/main/java/io/kafbat/ui/screens/topics/TopicDetails.java
  e2e-tests/src/main/java/io/kafbat/ui/settings/BaseSource.java
  e2e-tests/src/main/java/io/kafbat/ui/settings/drivers/WebDriver.java
  frontend/src/components/Nav/ClusterMenu/ClusterMenu.tsx
  frontend/src/components/Nav/Menu/MenuColorPicker/MenuColorPicker.styled.ts
  frontend/src/components/Nav/Menu/MenuColorPicker/MenuColorPicker.tsx
  frontend/src/components/Nav/Menu/MenuColorPicker/__tests__/MenuColorPicker.spec.tsx
  frontend/src/components/Nav/Menu/MenuTab.tsx
  frontend/src/components/Nav/Menu/__tests__/MenuTab.spec.tsx
  frontend/src/components/Nav/Menu/styled.ts
  frontend/src/components/Nav/Nav.styled.ts
  frontend/src/components/common/Dropdown/Dropdown.styled.ts
  frontend/src/components/common/Dropdown/Dropdown.tsx
  frontend/src/components/common/Icons/ColorPickerIcon.tsx
  frontend/src/theme/theme.ts
Labels: scope/frontend, type/feature, hacktoberfest-accepted, area/ux, status/triage/manual, status/triage/completed

#946 BE: RBAC: Fix RBAC rules validations
  api/src/main/java/io/kafbat/ui/model/rbac/Role.java
Labels: scope/backend, type/bug, area/rbac, status/triage/completed

#663 RBAC: Make it possible to use regex for values
  api/src/main/java/io/kafbat/ui/model/rbac/Subject.java
  api/src/main/java/io/kafbat/ui/service/rbac/extractor/CognitoAuthorityExtractor.java
  api/src/main/java/io/kafbat/ui/service/rbac/extractor/GithubAuthorityExtractor.java
  api/src/main/java/io/kafbat/ui/service/rbac/extractor/GoogleAuthorityExtractor.java
  api/src/main/java/io/kafbat/ui/service/rbac/extractor/OauthAuthorityExtractor.java
  api/src/main/java/io/kafbat/ui/service/rbac/extractor/RbacActiveDirectoryAuthoritiesExtractor.java
  api/src/main/java/io/kafbat/ui/service/rbac/extractor/RbacLdapAuthoritiesExtractor.java
  api/src/test/java/io/kafbat/ui/config/RegexBasedProviderAuthorityExtractorTest.java
  api/src/test/resources/roles_definition.yaml
Labels: type/enhancement, scope/backend, area/rbac, status/triage/completed

#957 BE: Chore: Bump Spring Boot to 3.4.4
  gradle/libs.versions.toml
Labels: scope/backend, type/dependencies, status/triage/completed

#443 fix Infra: Do not run e2e reports task on forks #313
  .github/workflows/e2e-run.yml
Labels: type/enhancement, scope/infra, hacktoberfest-accepted, status/triage/completed

#922 Update: GitHub Actions workflows to use specific versions of actions
  .github/workflows/backend_tests.yml
  .github/workflows/block_merge.yml
  .github/workflows/branch-deploy.yml
  .github/workflows/branch-remove.yml
  .github/workflows/build-public-image.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/cve_checks.yml
  .github/workflows/delete-public-image.yml
  .github/workflows/docker_build.yml
  .github/workflows/docker_publish.yml
  .github/workflows/e2e-run.yml
  .github/workflows/frontend_tests.yml
  .github/workflows/infra_discord_hook.yml
  .github/workflows/main.yml
  .github/workflows/md-links.yml
  .github/workflows/pr_linter.yml
  .github/workflows/release-serde-api.yml
  .github/workflows/release.yml
  .github/workflows/release_drafter.yml
  .github/workflows/separate_env_public_create.yml
  .github/workflows/welcome-first-time-contributors.yml
  .github/workflows/workflow_linter.yml
Labels: type/security, scope/infra, status/triage/completed

#961 Infra: Group dependabot updates
  .github/dependabot.yml
Labels: scope/infra, status/triage/completed
