Repository kafbat/kafka-ui, pull requests merged in 2025-04, with the labels that each got.

#994 FE: Messages: Format JSON arrays
  frontend/src/components/Topics/Topic/Messages/MessageContent/MessageContent.tsx
Labels: type/enhancement, scope/frontend, area/messages, status/triage/completed

#1016 UX: Auth: Logout button is inaccessible
  frontend/src/components/NavBar/UserInfo/UserInfo.styled.ts
  frontend/src/components/NavBar/UserInfo/UserInfo.tsx
  frontend/src/components/common/Dropdown/DropdownItem.tsx
Labels: scope/frontend, type/bug, area/ux, area/auth, status/triage/completed

#1029 Added Powered by JetBrains
  README.md
Labels: status/triage/manual, status/triage/completed

#1032 docs: use syntax highlighting
  README.md
Labels: status/triage/manual, status/triage/completed

#799 BE: Impl a default timeout for http requests
  api/src/main/java/io/kafbat/ui/client/RetryingKafkaConnectClient.java
  api/src/main/java/io/kafbat/ui/config/ClustersProperties.java
  api/src/main/java/io/kafbat/ui/config/WebclientProperties.java
  api/src/main/java/io/kafbat/ui/service/KafkaClusterFactory.java
  api/src/main/java/io/kafbat/ui/util/WebClientConfigurator.java
  contract/src/main/resources/swagger/kafbat-ui-api.yaml
Labels: type/enhancement, scope/backend, status/triage/completed

#1019 BE: Auth: Fix LDAP SPEL
  api/src/main/java/io/kafbat/ui/config/auth/LdapProperties.java
  api/src/main/java/io/kafbat/ui/config/auth/LdapSecurityConfig.java
Labels: scope/backend, type/bug, area/auth, status/triage/completed

#1036 BE: Extend config sanitizer patterns
  api/src/main/java/io/kafbat/ui/service/KafkaConfigSanitizer.java
  api/src/test/java/io/kafbat/ui/service/KafkaConfigSanitizerTest.java
Labels: scope/backend, type/chore, status/triage/completed

#607 FE: Fix 'Online Partitions' column
  e2e-tests/src/main/java/io/kafbat/ui/screens/brokers/BrokersList.java
  frontend/src/components/Brokers/BrokersList/SkewHeader/SkewHeader.tsx
  frontend/src/components/Brokers/BrokersList/TableCells/TableCells.tsx
  frontend/src/components/Brokers/BrokersList/lib/types.ts
  frontend/src/components/Brokers/BrokersList/lib/utils.ts
Labels: scope/frontend, type/bug, hacktoberfest-accepted, status/triage/completed, area/brokers

#767 BE: RBAC: Implement RBAC tests
  api/src/test/java/io/kafbat/ui/service/rbac/AccessControlServiceRbacDisabledTest.java
  api/src/test/java/io/kafbat/ui/service/rbac/AccessControlServiceRbacEnabledTest.java
  api/src/test/java/io/kafbat/ui/service/rbac/MockedRbacUtils.java
  api/src/test/java/io/kafbat/ui/service/rbac/RbacClusterConfigTest.java
  api/src/test/java/io/kafbat/ui/service/rbac/RbacClusterMistakenTest.java
  api/src/test/java/io/kafbat/ui/service/rbac/RbacEditTopicTest.java
  api/src/test/java/io/kafbat/ui/service/rbac/RbacTopicCreationTest.java
Labels: scope/backend, type/chore, area/rbac, status/triage/completed

#1042 BE: Fix build
  api/src/test/java/io/kafbat/ui/service/rbac/MockedRbacUtils.java
  api/src/test/java/io/kafbat/ui/service/rbac/RbacClusterMistakenTest.java
  api/src/test/java/io/kafbat/ui/service/rbac/RbacEditTopicTest.java
  api/src/test/java/io/kafbat/ui/service/rbac/RbacTopicCreationTest.java
Labels: scope/backend, type/chore, status/triage/completed

#1047 BE: Chore: Bump Spring Boot to 3.4.5
  gradle/libs.versions.toml
Labels: scope/backend, type/security, type/dependencies, status/triage/completed
