Repository kafbat/kafka-ui, pull requests merged in 2025-09, with the labels that each got.

#1151 BE: Implement app restart on dynamic config change
  api/src/main/java/io/kafbat/ui/config/auth/RoleBasedAccessControlProperties.java
  api/src/main/java/io/kafbat/ui/service/app/ConfigReloadService.java
  api/src/main/java/io/kafbat/ui/service/rbac/AccessControlService.java
  api/src/main/java/io/kafbat/ui/util/DynamicConfigOperations.java
  api/src/main/java/io/kafbat/ui/util/MultiFileWatcher.java
Labels: type/enhancement, scope/backend, area/wizard, status/triage/completed

#1217 FE: UX: Show N/A when consumer lag is null
  frontend/src/components/ConsumerGroups/Details/ListItem.tsx
Labels: scope/frontend, type/bug, area/ux, area/consumers, status/triage/completed

#1273 FE: Manual column width for Consumers and Topics tables
  frontend/src/components/ConsumerGroups/List.tsx
  frontend/src/components/Topics/List/TopicTable.tsx
Labels: area/topics, status/triage/manual, status/triage/completed

#1329 Infra: Ignore Netty updates
  .github/dependabot.yml
Labels: scope/infra, type/chore, status/triage/completed

#1346 FE: Fixed schema sort
  frontend/src/components/Schemas/List/List.tsx
Labels: status/triage/completed

#1347 Fixed nulls sorting
  api/src/main/java/io/kafbat/ui/controller/SchemasController.java
Labels: status/triage/completed

#1351 Open cluster menu if cluster name in url changed
  frontend/src/components/Nav/ClusterMenu/ClusterMenu.tsx
Labels: status/triage/manual, status/triage/completed

#1353 BE: Fixed filter comparators
  api/src/main/java/io/kafbat/ui/service/ConsumerGroupService.java
  api/src/main/java/io/kafbat/ui/service/KafkaConnectService.java
  api/src/main/java/io/kafbat/ui/service/index/NgramFilter.java
  api/src/main/java/io/kafbat/ui/service/index/SchemasFilter.java
  api/src/test/java/io/kafbat/ui/service/index/AbstractNgramFilterTest.java
  api/src/test/java/io/kafbat/ui/service/index/AclBindingFilterTest.java
  api/src/test/java/io/kafbat/ui/service/index/ConsumerGroupFilterTest.java
  api/src/test/java/io/kafbat/ui/service/index/KafkaConnectNgramFilterTest.java
  api/src/test/java/io/kafbat/ui/service/index/SchemasFilterTest.java
Labels: scope/backend, status/triage/completed
