Repository kafbat/kafka-ui, pull requests merged in 2025-07, with the labels that each got.

#1155 Redirect to consumer group page after offset reset
  frontend/src/components/ConsumerGroups/Details/ResetOffsets/Form.tsx
Labels: type/enhancement, area/ux, status/triage/manual, status/triage/completed

#1143 BE: Chore: Bump Spring Boot to 3.5.3
  api/build.gradle
  gradle/libs.versions.toml
Labels: scope/backend, type/security, type/dependencies, status/triage/completed

#1179 BE: Chore: Bump Apache Commons-lang3 from 3.12.0 to 3.18.0
  gradle/libs.versions.toml
Labels: scope/backend, type/security, type/dependencies, status/triage/completed

#1180 BE: Chore: Overwrite nimbus-jose-jwt temporarily to fix CVE-2025-5386
  api/build.gradle
  gradle/libs.versions.toml
Labels: scope/backend, type/security, type/dependencies, status/triage/completed

#1182 Infra: Replace usage of Dependabot's reviewers with CODEOWNERS
  .github/CODEOWNERS
  .github/dependabot.yml
Labels: type/enhancement, scope/infra, status/triage/completed

#1185 BE: Chore: Fix documentation typo
  api/build.gradle
  gradle/libs.versions.toml
Labels: scope/infra, type/chore, status/triage/completed

#1178 FE: RBAC problem for broker settings
  frontend/src/components/Brokers/Broker/Configs/TableComponents/InputCell/InputCellViewMode.tsx
  frontend/src/components/common/ActionComponent/ActionButton/ActionCanButton/ActionCanButton.tsx
Labels: scope/frontend, type/bug, area/rbac, status/triage/manual, status/triage/completed

#1181 Infra: Create dedicated Dependabot group for Spring dependencies
  .github/dependabot.yml
Labels: type/enhancement, scope/infra, status/triage/completed

#1173 FE: Customize user timezone
  frontend/src/components/ConsumerGroups/Details/ResetOffsets/Form.tsx
  frontend/src/components/NavBar/NavBar.tsx
  frontend/src/components/NavBar/UserTimezone/UserTimezone.styled.ts
  frontend/src/components/NavBar/UserTimezone/UserTimezone.tsx
  frontend/src/components/Topics/Topic/Messages/Message.tsx
  frontend/src/components/Topics/Topic/Messages/MessageContent/MessageContent.tsx
  frontend/src/components/Topics/Topic/Messages/__test__/Message.spec.tsx
  frontend/src/components/Topics/Topic/Statistics/Indicators/Total.tsx
  frontend/src/components/Topics/Topic/Statistics/Metrics.tsx
  frontend/src/components/Topics/Topic/Statistics/PartitionInfoRow.tsx
  frontend/src/components/Version/Version.tsx
  frontend/src/components/common/Dropdown/Dropdown.styled.ts
  frontend/src/components/common/Dropdown/Dropdown.tsx
  frontend/src/components/common/Icons/ChevronDownIcon.tsx
  frontend/src/components/common/NewTable/TimestampCell.tsx
  frontend/src/components/common/NewTable/__test__/Table.spec.tsx
  frontend/src/components/globalCss.ts
  frontend/src/lib/dateTimeHelpers.ts
  frontend/src/lib/hooks/__tests__/dateTimeHelpers.spec.ts
  frontend/src/lib/hooks/useLocalStorage.ts
  frontend/src/lib/hooks/useTimezones.ts
  frontend/src/theme/theme.ts
Labels: scope/frontend, type/feature, area/ux, status/triage/completed

#509 Serde: Enable header modifications by custom serializer
  api/src/main/java/io/kafbat/ui/serdes/ProducerRecordCreator.java
  api/src/main/java/io/kafbat/ui/serdes/SerdeInstance.java
  serde-api/build.gradle
  serde-api/src/main/java/io/kafbat/ui/serde/api/Serde.java
Labels: type/enhancement, scope/backend, hacktoberfest-accepted, area/serde, status/triage/completed

#1225 E2E Playwright: Topic message menu fix
  e2e-playwright/src/features/TopicsMessages.feature
  e2e-playwright/src/pages/Topics/TopicsTopickNameLocators.ts
  e2e-playwright/src/steps/ProduceMessages.ts
Labels: status/triage/manual, status/triage/completed

#1231 FE: Add Plain UTC timezone
  frontend/src/lib/hooks/useTimezones.ts
Labels: status/triage/manual, status/triage/completed
