Repository kafbat/kafka-ui, pull requests merged in 2025-10, with the labels that each got.

#1397 Fix duplicate entry in docker-compose documentation
  documentation/compose/DOCKER_COMPOSE.md
Labels: status/triage/completed

#1403 FE: Reduce nav bar height
  frontend/src/components/Nav/Menu/styled.ts
Labels: hacktoberfest-accepted, status/triage/manual, status/triage/completed

#1381 BE: Serde: Impl MM2 serdes
  api/src/main/java/io/kafbat/ui/serdes/BuiltInSerde.java
  api/src/main/java/io/kafbat/ui/serdes/ClusterSerdes.java
  api/src/main/java/io/kafbat/ui/serdes/SerdesInitializer.java
  api/src/main/java/io/kafbat/ui/serdes/builtin/AvroEmbeddedSerde.java
  api/src/main/java/io/kafbat/ui/serdes/builtin/Base64Serde.java
  api/src/main/java/io/kafbat/ui/serdes/builtin/ConsumerOffsetsSerde.java
  api/src/main/java/io/kafbat/ui/serdes/builtin/HexSerde.java
  api/src/main/java/io/kafbat/ui/serdes/builtin/Int32Serde.java
  api/src/main/java/io/kafbat/ui/serdes/builtin/Int64Serde.java
  api/src/main/java/io/kafbat/ui/serdes/builtin/ProtobufFileSerde.java
  api/src/main/java/io/kafbat/ui/serdes/builtin/ProtobufRawSerde.java
  api/src/main/java/io/kafbat/ui/serdes/builtin/StringSerde.java
  api/src/main/java/io/kafbat/ui/serdes/builtin/StructSerde.java
  api/src/main/java/io/kafbat/ui/serdes/builtin/UInt32Serde.java
  api/src/main/java/io/kafbat/ui/serdes/builtin/UInt64Serde.java
  api/src/main/java/io/kafbat/ui/serdes/builtin/UuidBinarySerde.java
  api/src/main/java/io/kafbat/ui/serdes/builtin/mm2/CheckpointSerde.java
  api/src/main/java/io/kafbat/ui/serdes/builtin/mm2/HeartbeatSerde.java
  api/src/main/java/io/kafbat/ui/serdes/builtin/mm2/MirrorMakerSerde.java
  api/src/main/java/io/kafbat/ui/serdes/builtin/mm2/OffsetSyncSerde.java
  api/src/main/java/io/kafbat/ui/serdes/builtin/sr/SchemaRegistrySerde.java
  api/src/test/java/io/kafbat/ui/emitter/CursorTest.java
  api/src/test/java/io/kafbat/ui/emitter/TailingEmitterTest.java
  api/src/test/java/io/kafbat/ui/serdes/SerdesInitializerTest.java
  api/src/test/java/io/kafbat/ui/serdes/builtin/mm2/CheckpointSerdeTest.java
  api/src/test/java/io/kafbat/ui/serdes/builtin/mm2/HeartbeatSerdeTest.java
  api/src/test/java/io/kafbat/ui/serdes/builtin/mm2/MirrorMakerSerdesAbstractTest.java
  api/src/test/java/io/kafbat/ui/serdes/builtin/mm2/OffsetSyncSerdeTest.java
  api/src/test/java/io/kafbat/ui/service/MessagesServiceTest.java
  api/src/test/java/io/kafbat/ui/service/RecordEmitterTest.java
  api/src/test/java/io/kafbat/ui/service/SendAndReadTests.java
Labels: scope/backend, type/feature, hacktoberfest-accepted, area/serde

#1396 Issues/1333 optional fts
  api/src/main/java/io/kafbat/ui/config/ClustersProperties.java
  api/src/main/java/io/kafbat/ui/controller/AclsController.java
  api/src/main/java/io/kafbat/ui/controller/ConsumerGroupsController.java
  api/src/main/java/io/kafbat/ui/controller/KafkaConnectController.java
  api/src/main/java/io/kafbat/ui/controller/SchemasController.java
  api/src/main/java/io/kafbat/ui/controller/TopicsController.java
  api/src/main/java/io/kafbat/ui/model/ClusterFeature.java
  api/src/main/java/io/kafbat/ui/service/FeatureService.java
  api/src/main/java/io/kafbat/ui/service/KafkaConnectService.java
  api/src/main/java/io/kafbat/ui/service/TopicsService.java
  api/src/main/java/io/kafbat/ui/service/acl/AclsService.java
  api/src/main/java/io/kafbat/ui/service/index/FilterTopicIndex.java
  api/src/main/java/io/kafbat/ui/service/index/LuceneTopicsIndex.java
  api/src/main/java/io/kafbat/ui/service/index/TopicsIndex.java
  api/src/test/java/io/kafbat/ui/service/SchemaRegistryPaginationTest.java
  api/src/test/java/io/kafbat/ui/service/TopicsServicePaginationTest.java
  api/src/test/java/io/kafbat/ui/service/index/LuceneTopicsIndexTest.java
  api/src/test/java/io/kafbat/ui/service/mcp/McpSpecificationGeneratorTest.java
  contract-typespec/api/acls.tsp
  contract-typespec/api/clusters.tsp
  contract-typespec/api/consumer-groups.tsp
  contract-typespec/api/kafka-connect.tsp
  contract-typespec/api/schemas.tsp
  contract-typespec/api/topics.tsp
  contract/src/main/resources/swagger/kafbat-ui-api.yaml
Labels: hacktoberfest-accepted, status/triage/completed

#1411 BE: Fix alpine CVEs
  api/Dockerfile
Labels: scope/backend, type/security, status/triage/completed
